matrix:
  include:
    - name: "Back-office's backend (API & Docker)"
      language: python
      python:
        - '3.4'
      cache:
        pip: true
      env:
        - DEFAULT_INTERFACE=eth0 # needed to setup django context
      before_script:
        - docker pull coaxisasp/coaxisopt_daemon:latest
        - cd ./daemon/
        - make -f help-me.mk build
      script:
        - cd ../backend/
        - make install test-api DEFAULT_INTERFACE=$DEFAULT_INTERFACE

    - name: "Back-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '4.8'
      cache:
        yarn: true
      before_install:
        - cd frontend/
      install:
        - yarn install --frozen-lockfile
      script:
        - yarn test

    - name: "Front-office's MAST (mast-utils)"
      language: bash
      install:
        - make
      script:
        - make test-mast

    - name: "Front-office's backend (API & network)"
      language: python
      python:
        - '3.4'
      cache:
        pip: true
      script:
        - make test-frontoffice-backend

    - name: "Front-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '8.12.0'
      cache:
        yarn: true
      install:
        - pushd ./daemon/frontend/
        - yarn install --frozen-lockfile
      script:
        - popd
        - make test-frontoffice-frontend

    - name: "Front-office's End to end"
      language: node_js
      node_js:
        - '10'
      cache:
        yarn: true
        directories:
          - ~/.cache
      install:
        - pushd ./daemon/frontend/
        - yarn install --frozen-lockfile
      script:
        - popd
        - make test-frontoffice-end-to-end

notifications:
  email: false
