matrix:
  include:
    - name: "Back-office's backend (API & Docker)"
      language: python
      python:
        - '3.4'
      before_install:
        - cd backend/
      install:
        - make install
      script:
        - make test-api

    - name: "Back-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '4.8'
      before_install:
        - cd frontend/
      install:
        - yarn install --frozen-lockfile
      script:
        - yarn test

    - name: "Front-office's MAST (mast-utils)"
      language: bash
      install:
        - make
      script:
        - make test-mast

    - name: "Front-office's backend (API & network)"
      language: python
      python:
        - '3.4'
      script:
        - make test-frontoffice-backend

    - name: "Front-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '8.12.0'
      install:
        - yarn install --frozen-lockfile
      script:
        - make test-frontoffice-frontend

    - name: "Front-office's End to end"
      language: node_js
      node_js:
        - '10'
      cache:
        npm: true
        directories:
          - ~/.cache
      install:
        - npm ci
      script:
        - make test-frontoffice-end-to-end

notifications:
  email: false
