jobs:
  include:
    - stage: test
      name: "Back-office's backend (API & Docker)"
      language: python
      python:
        - '3.4'
      cache:
        pip: true
      env:
        - DEFAULT_INTERFACE=eth0 # needed to setup django context
      before_script:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - docker pull coaxisasp/coaxisopt_daemon:latest
        - cd ./daemon/
        - make -f help-me.mk build
      script:
        - cd ../backend/
        - make install test-api DEFAULT_INTERFACE=$DEFAULT_INTERFACE

    - stage: test
      name: "Back-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '4.8'
      cache:
        yarn: true
      before_install:
        - cd frontend/
      install:
        - yarn install --frozen-lockfile
      script:
        - yarn test

    - stage: test
      name: "Front-office's MAST (mast-utils)"
      language: bash
      before_script:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - make dev
      script:
        - make test-mast

    - stage: test
      name: "Front-office's backend (API & network)"
      language: python
      python:
        - '3.4'
      cache:
        pip: true
      before_script:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      script:
        - make test-frontoffice-backend

    - stage: test
      name: "Front-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '8.12.0'
      cache:
        yarn: true
      install:
        - pushd ./daemon/frontend/
        - yarn install --frozen-lockfile
      script:
        - popd
        - make test-frontoffice-frontend

    - stage: test
      name: "Front-office's End to end"
      language: node_js
      node_js:
        - '10'
      cache:
        yarn: true
        directories:
          - ~/.cache
      install:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - pushd ./daemon/frontend/
        - yarn install --frozen-lockfile
      script:
        - popd
        - make test-frontoffice-end-to-end

    - stage: release
      language: bash
      if: tag IS present
      before_script:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      script:
        - make release

notifications:
  email: false
