matrix:
  include:
    - name: "Back-office's backend (API & Docker)"
      language: python
      python:
        - '3.4'
      env:
        - DEFAULT_INTERFACE=eth0 # needed to setup django context
      before_install:
        - docker pull coaxisasp/coaxisopt_daemon:latest
      install:
        - cd backend/
        - make install
      script:
        - make test-api DEFAULT_INTERFACE=$DEFAULT_INTERFACE

    - name: "Back-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '4.8'
      before_install:
        - cd frontend/
      install:
        - yarn install --frozen-lockfile
      script:
        - yarn test

    - name: "Front-office's MAST (mast-utils)"
      language: bash
      install:
        - make
      script:
        - make test-mast

    - name: "Front-office's backend (API & network)"
      language: python
      python:
        - '3.4'
      script:
        - make test-frontoffice-backend

    - name: "Front-office's front-end (Vue.js)"
      language: node_js
      node_js:
        - '8.12.0'
      install:
        - pushd ./daemon/frontend/
        - yarn install --frozen-lockfile
      script:
        - popd
        - make test-frontoffice-frontend

    - name: "Front-office's End to end"
      language: node_js
      node_js:
        - '10'
      cache:
        npm: true
        directories:
          - ~/.cache
      install:
        - npm ci
      script:
        - make test-frontoffice-end-to-end

notifications:
  email: false
