matrix:
  include:
    - name: "Back-office's backend"
      language: python
      python:
        - '3.4'
      script:
        - make test-backoffice-backend

    - name: "Back-office's front-end"
      language: node_js
      node_js:
        - '4.8'
      script:
        - make test-backoffice-frontend

    - name: "Front-office's backend"
      language: python
      python:
        - '3.4'
      script:
        - make test-frontoffice-backend

    - name: "Front-office's front-end"
      language: node_js
      node_js:
        - '4.8'
      script:
        - make test-frontoffice-frontend

notifications:
  email: false
