matrix:
  include:
    - name: "Back-office's API"
      language: python
      python: 
        - "3.4"
      env:
      - DEFAULT_INTERFACE=eth0
      before_install:
        - cd backend/
      install: 
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - name: "Back-office's front-end"
      language: node_js
      node_js:
        - "4.8"
      before_install:
        - cd frontend/
      install:
        - yarn install
      script:
        - yarn test

    - name: "Front-office's API"
      language: python
      python: 
        - "3.4"
      before_install:
        - cd daemon/
        - sudo apt-get update
      install: 
        - make -f help-me.mk install-dependencies
      script:
        - make -f help-me.mk test-api

    - name: "Front-office's front-end"
      language: node_js
      node_js:
        - "4.8"
      before_install:
        - cd daemon/frontend/
      install:
        - yarn install
      script:
        - yarn test

notifications:
  email: false