version: '2'
services:
  daemon:
    build: ./daemon
    image: coaxisopt_daemon
    ports:
      - "5000:5000"
      - "80:80"
    volumes:
      - config:/etc/mast
    volumes_from:
      - backend
      - frontend
    links:
      - opt-box
      - backend
      - frontend
  backend:
    build: ./backend
    volumes:
      - database:/backend/database
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
     - "8080:8080"

  # demo box
  opt-box:
      build: ./opt-box/
      ports:
        - "22:22"

volumes:
  database:
  config: