version: '2'
services:
  backend:
    restart: always
    volumes:
      - backend:/backend
    environment:
      - DEFAULT_INTERFACE=ens192
  frontend:
    restart: always
  nginx:
    restart: always
volumes:
  backend:
  frontend:
