version: '2'
services:
  daemon:
    build: ./
    ports:
      - "80:80"
    links:
      - opt-box:opt-box
    volumes:
      - ./webapp:/var/www/html/webapp
      - config:/etc/mast
    extra_hosts:
      - "mon-client.opt:127.0.0.1"
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - database:/backend/database
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
  opt-box:
      build: ./opt-box/
      ports:
        - "22:22"

volumes:
  database:
  config:
    driver: local