version: '2.2'

services:
  backend:
    build:
    context: ./backend
    cache_from:
      - coaxisasp/coaxisopt_backend
    image: coaxisopt_backend
    container_name: coaxisopt_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8000:8000'

  frontend:
    build:
    context: ./frontend
    cache_from:
      - coaxisasp/coaxisopt_frontend
    image: coaxisopt_frontend
    container_name: coaxisopt_frontend
    ports:
      - '8080:8080'

  nginx:
    build:
    context: ./nginx
    cache_from:
      - coaxisasp/coaxisopt_nginx
    image: coaxisopt_nginx
    container_name: coaxisopt_nginx
    ports:
      - '80:80'
    volumes_from:
      - backend
    links:
      - backend
      - frontend

volumes:
  database:
  config:
