version: '2'

services:
  daemon:
    environment:
      - FLASK_APP=/daemon/api/views.py
      - FLASK_DEBUG=1
    volumes:
      - ./daemon/api:/daemon/api
    command: supervisord
  backend:
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: npm run dev
volumes:
  node_modules:
