version: '2'

services:
  daemon:
      build: ./daemon
      image: coaxisopt_daemon
  backend:
    volumes:
      - ./backend:/backend
    environment:
      - DEFAULT_INTERFACE=wlp4s0
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: npm run dev
volumes:
  node_modules:
