version: '2'
services:
  backend:
    build: ./backend
    volumes:
      - database:/backend/database
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
     - "8080:8080"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes_from:
      - backend
    links:
      - backend
      - frontend

volumes:
  database:
  config:
