version: '2'

services:
  daemon:
    environment:
      - FLASK_APP=/api/api.py
      - FLASK_DEBUG=1
    volumes:
      - ./daemon/api:/api
    command: python -m flask run --host=0.0.0.0
  backend:
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: npm run dev
volumes:
  node_modules:
