version: '2'
services:
  daemon:
    build: ./
    ports:
      - "80:80"
    links:
      - opt-box:opt-box
    volumes:
      - ./webapp:/var/www/html/webapp
      - config:/etc/mast
  opt-box:
      build: ./opt-box/
      ports:
        - "22:22"

volumes:
  config:
    driver: local