version: '2'
services:
  daemon:
    restart: always
  backend:
    restart: always
    volumes:
      - backend:/backend
    environment:
      - DEFAULT_INTERFACE=ens192
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/prod.conf
  frontend:
    restart: always
  nginx:
    restart: always
volumes:
  backend:
  frontend: