version: '2'
services:
  daemon:
    build: ./daemon
    ports:
      - "81:80"
    links:
      - opt-box:opt-box
    volumes:
#      - ./webapp:/var/www/html/webapp
      - config:/etc/mast
    volumes_from:
      - backend
    extra_hosts:
      - "mon-client.opt:127.0.0.1"
    links:
      - backend
  backend:
    build: ./backend
    volumes:
      - database:/backend/database
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
     - "8080:8080"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend

  # demo box
  box:
      build: ./opt-box/
      ports:
        - "22:22"

volumes:
  database:
  config: