version: '2'
services:
  daemon:
    build: ./
    cache_from:
      - coaxisasp/coaxisopt_daemon
    image: coaxisopt_daemon
    container_name: coaxisopt_daemon
    ports:
      - "80:80"
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./api:/api
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
      - ./mast:/etc/init.d/mast
      - ~/.bash_history:/root/.bash_history
      - ./test:/test
      - ./makefile:/usr/sbin/mast-utils
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/dev.conf
volumes:
  daemon:
  node_modules: